### ISSUE TITLE
Build on Mac stops at: Running "build-atom-shell" task

### ISSUE THREAD

**Issue by erusev** [atom/electron-starter#86]
When I run:

```
script/build
```

I get:

``` 
Node: v0.10.38
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓
Running "build-atom-shell" task
```

It stops at that last line an never continues.

**Comment by jgeurts** [comment]
It's likely working, just slowly... on a good day, that task will take 30 min for me. I've heard others taking as long as 8 hours for that task to complete with a poor network.

**Comment by westoque** [comment]
@erusev It's because it's also downloading a big file 1.7G file. You can see more of what's happening if you run `script/build -v`, NOTE the `-v` flag to make it run in verbose.

Also, the sad thing is that every time you rebuild, it will clean the build, thus deleting this huge file and then you'll have to download it again. I managed to run around it by downloading the file and intercepting this call from a local server and just returning the 1.7G file.

**Comment by erusev** [comment]
This explains it, thanks.
